service: liquid-automations

frameworkVersion: "=1.19"

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  role: arn:aws:iam::860963740950:role/${self:service}-${opt:stage}-runtime
  environment: ${file(envs.yml):${opt:stage}}
  stackTags:
    project: liquid-automations
    stage: ${opt:stage}
  deploymentBucket:
    name: ${self:service}-${opt:stage}-deployments

functions:
  helloWorld:
    handler: dist/handlers.helloWorld
    timeout: 60
    memorySize: 128
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
